# Generated by Django 3.2.7 on 2021-09-29 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorys',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
