# Generated by Django 3.2.7 on 2021-09-29 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_categorys_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorys',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
