# Generated by Django 3.2.7 on 2021-09-29 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_categorys_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorys',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
