# Generated by Django 3.2.8 on 2021-10-10 00:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='update',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='post.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='update',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
